#!/usr/bin/env bash

# SPREADSHEETID should be in .env
set -a; test -f .env && source .env; set +a

declare TARGET="Lctns!A1:C1"
declare TOKEN_DATA_FILE="google-oauth.json"
declare TOKEN

TOKEN="$(jq -r '.access_token' $TOKEN_DATA_FILE)"

cat <<EOPAYLOAD |
{
  "range": "Lctns!A1:C1",
  "majorDimension": "ROWS",
  "values": [
    ["1", "2", "three"]
  ]
}
EOPAYLOAD
curl \
    --verbose \
    --url "https://sheets.googleapis.com/v4/spreadsheets/$SPREADSHEETID/values/$TARGET:append?valueInputOption=RAW" \
    --header "Authorization: Bearer $TOKEN" \
    --header 'Content-Type: application/json' \
    --data @-
